-- ID: 1
insert into TB_NATUREZA_CONTA (CD_LANCAMENTO_CONTA, CD_SITUACAO_NATUREZA_CONTA, ID_ENTIDADE_CONTROLE, TX_DESCRICAO_NATUREZA_CONTA, DH_REGISTRO_NATUREZA_CONTA)
values (1, 1, 1, 'Natureza Credito Teste', CURRENT_TIMESTAMP());

-- ID: 2
insert into TB_NATUREZA_CONTA (CD_LANCAMENTO_CONTA, CD_SITUACAO_NATUREZA_CONTA, ID_ENTIDADE_CONTROLE, TX_DESCRICAO_NATUREZA_CONTA, DH_REGISTRO_NATUREZA_CONTA)
values (2, 1, 1, 'Natureza Debito Teste', CURRENT_TIMESTAMP());

-- ID: 1 
insert into TB_DESPESA_FIXA (CD_TIPO_SITUACAO_DESPESA_FIXA, CD_FORMA_LIQUIDACAO_DESPESA_FIXA, ID_NATUREZA_CONTA_DESPESA_FIXA, ID_ENTIDADE_CONTROLE, TX_DESCRICAO_DESPESA_FIXA, DD_VENCIMENTO_DESPESA_FIXA, VL_DESPESA_FIXA, DH_REGISTRO_DESPESA_FIXA) 
values (1, 1, 2, 1, 'Despesa Fixa 01 Teste', 10, 999.01, CURRENT_TIMESTAMP());
-- ID: 2
insert into TB_DESPESA_FIXA (CD_TIPO_SITUACAO_DESPESA_FIXA, CD_FORMA_LIQUIDACAO_DESPESA_FIXA, ID_NATUREZA_CONTA_DESPESA_FIXA, ID_ENTIDADE_CONTROLE, TX_DESCRICAO_DESPESA_FIXA, DD_VENCIMENTO_DESPESA_FIXA, VL_DESPESA_FIXA, DH_REGISTRO_DESPESA_FIXA) 
values (1, 1, 2, 1, 'Despesa Fixa 02 Teste', 10, 999.02, CURRENT_TIMESTAMP());

-- ID: 1
insert into TB_DESPESA_MENSAL (ID_DESPESA_FIXA, ID_NATUREZA_DESPESA, CD_FORMA_LIQUIDACAO_DESPESA, ID_ENTIDADE_CONTROLE, IN_DESPESA_PARCELADA, CD_VINCULO_DESPESA_PARCELADA, TX_DESCRICAO_DESPESA, DT_VENCIMENTO_DESPESA, VL_DESPESA, CD_VINCULO_FORMA_LIQUIDACAO, IN_DESPESA_LIQUIDADA, TX_OBSERVACAO_DESPESA, DH_LIQUIDACAO_DESPESA, VL_DESCONTO_LIQUIDACAO_DESPESA, VL_MULTA_JUROS_LIQUIDACAO_DESPESA, VL_TOTAL_LIQUIDACAO_DESPESA, DH_REGISTRO_DESPESA)
values (1, 2, 1, 1, 0, null, 'Despesa Mensal 01 Teste', CURRENT_TIMESTAMP(), 999.01, 1, 1, '', CURRENT_DATE(), 0.0, 0.0, 999.01, CURRENT_TIMESTAMP());